#ifndef PLATFORMERGAMECPP_MODEL_CONSTANTS_HPP_
#define PLATFORMERGAMECPP_MODEL_CONSTANTS_HPP_

namespace Platformer {
const int BLOCK_SIZE = 1000;
const int PLAYER_SPEED = 150;
const int FREEFALL_ACCELERATION = 10;
const int MAX_FIELD_SIZE = 1000;
const int BOTTOM_DEATH_BORDER = 20'000;
const float WALL_BOUNCE_COEFFICIENT = 0.5;
}  // namespace Platformer

#endif  // PLATFORMERGAMECPP_MODEL_CONSTANTS_HPP_
