#ifndef PLATFORMERGAMECPP_MODEL_CONSTANTS_HPP_
#define PLATFORMERGAMECPP_MODEL_CONSTANTS_HPP_

namespace Platformer {
const int BLOCK_SIZE = 1000;
const int PLAYER_SPEED = 100;
const int FREEFALL_ACCELERATION = 5;
const int MAX_FIELD_SIZE = 1000;
const float WALL_BOUNCE_COEFFICIENT = 0.5;
}  // namespace Platformer

#endif  // PLATFORMERGAMECPP_MODEL_CONSTANTS_HPP_
